version: "3.8"

volumes:
  rabbit-volume: {}

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbit-volume:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: none # disable logs

  mongo:
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none # disable logs

  tickets-api:
    build: ../Services/Tickets.Api
    image: hc.tickets.api
    depends_on:
      - rabbitmq
      - mongo
    links:
      - rabbitmq
      - mongo
    ports:
      - 5750:80
    healthcheck:
      test: curl --fail -s http://localhost:80/hc
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s

  mail-notifications-api:
    build: ../Services/MailNotifications.Api
    image: hc.mail-notifications.api
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    restart: on-failure
    ports:
      - 5751:80
